#!/bin/sh

# copy this file to .git/hooks (i.e., overwrite the file .git/hooks/pre-commit)
# to perform source checks before commits

. $PWD/scripts/pre-commit

[ $? -eq 0 ] && make -j8 cairo=no CFLAGS+=-fstrict-aliasing opt=no 64bit=yes CC='ccache clang -fcolor-diagnostics'

[ $? -eq 0 ] && make cairo=no CFLAGS+=-fstrict-aliasing opt=no 64bit=yes -j2 sbgt

[ $? -eq 0 ] && make cairo=no CFLAGS+=-fstrict-aliasing opt=no 64bit=yes -j8 spgt
