#!/bin/bash

TEMPLATE=src/match/esa-bottomup

msg=\
"/*
  This file is autogenerated by
  appendsuffix.rb ${TEMPLATE}.gen ${suffix} BUinfo BUstate
  Manual edits will be lost.
*/"

for suffix in maxpairs shulen
do
  file=${TEMPLATE}-${suffix}.inc
  rm -f $file
  echo "$msg" > $file
  scripts/appendsuffix.rb ${TEMPLATE}.gen ${suffix} BUinfo BUstate >> $file
done
