#!/bin/bash

msg=\
"/*

  This file is autogenerated by $0.
  Manual edits will be lost by the next call of $0.

*/"

for i in rdjce rdjcv rdjo
do
  file=src/match/esa-bottomup-$i.inc
  rm -f $file
  echo "$msg" > $file
  scripts/appendsuffix.rb src/match/esa-bottomup.gen $i >> $file
done
