#/bin/sh
#tmp1 is 
#>the first 100000K of at1MB
#CAATTCCNGCCGCTCGCCTTTTTCCCCTTTTCCGTCTCTCCGATCTGCTCCCG
#TAGCTCTGAAGGTCCATACAAGGATATAAAAAAAAAAAAAAAAA
#YM

rm -rf ../indexdir/ ; rununique-test.sh 10 30 ${U8} tmp1

