#!/bin/sh

# copy this file to .git/hooks (i.e., overwrite the file .git/hooks/pre-commit)
# to perform source checks before commits

find "$PWD/src" \( -path "$PWD/src/external" -prune \) -o \
  \( -name "*.c" -o -name "*.h" \) -print0 | \
  xargs -0 "$PWD/scripts/src_check"
