#!/bin/sh

# copy this file to .git/hooks (i.e., overwrite the file .git/hooks/pre-commit)
# to perform source checks before commits

# different versions of git use different letters for deleted/removed files
FILES=`git diff --cached --name-status HEAD | \
  awk '$1 != "R" && $1 != "D" { print $2 }' | \
  grep -v -e 'src/external'                 | \
  grep -e '.*\.c$' -e '.*\.h$'`

if [ ${#FILES} -gt 0 ]
then
  $PWD/scripts/src_check $FILES
  if [ $? -eq 0 ]
  then
    APIS=`echo "$FILES" | grep -F "_api.h"`
    if [ ${#APIS} ]; then
      echo "WARNING: you are committing API headers:"
      git diff --cached $APIS
      exec < /dev/tty
      echo
      read -p "Are you sure? [yn]" reply
      echo
      case $reply in
        [Yy]* ) exit 0;;
        [Nn]* ) exit 1;;
        * ) echo "Please answer yes or no.";;
      esac
      exit 1
    fi
  fi
else
  exit 0
fi
