#!/bin/sh
#
# Copyright (c) 2007 Gordon Gremme <gremme@zbh.uni-hamburg.de>
# Copyright (c) 2007 Center for Bioinformatics, University of Hamburg
# See LICENSE file or http://genometools.org/license.html for license details.
#

if [ $# -le 1 ]
then
  echo "Usage: `basename $0` preprend_file file [...]" >&2
  echo "Prepend \"preprend_file\" to each \"file\" and replace it afterwards." >&2
  echo "The original \"file\" is saved as \"file.bac\"." >&2
  exit 1
fi

preprend_file=$1
shift

for FILE in $*
do
  TMPFILE=`mktemp`
  cp $FILE $FILE.bac
  cat $preprend_file $FILE > $TMPFILE
  if [ $? -eq 0 ]
  then
    # cat command succeeded -> overwrite file
    mv -f $TMPFILE $FILE
  else
    echo "`basename $0`: cat command failed, removing tmpfile"
    rm -f $TMPFILE
  fi
done
