#!/bin/sh
#
# Copyright (c) 2007 Gordon Gremme <gremme@zbh.uni-hamburg.de>
# Copyright (c) 2007 Center for Bioinformatics, University of Hamburg
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

if [ $# -le 1 ]
then
  echo "Usage: `basename $0` sed_command file [...]" >&2
  echo "Apply \"sed_command\" to each \"file\" and replace it afterwards." >&2
  echo "The original \"file\" is saved as \"file.bac\"." >&2
  exit 1
fi

sed_command=$1
shift

for FILE in $*
do
  TMPFILE=`mktemp`
  cp $FILE $FILE.bac
  sed "$sed_command" $FILE > $TMPFILE
  if [ $? -eq 0 ]
  then
    # sed command succeeded -> overwrite file
    mv -f $TMPFILE $FILE
  else
    echo "`basename $0`: sed command failed, removing tmpfile"
    rm -f $TMPFILE
  fi
done
