#!/bin/sh -e
#
# Copyright (c) 2006-2008 Gordon Gremme <gremme@zbh.uni-hamburg.de>
# Copyright (c) 2006-2008 Center for Bioinformatics, University of Hamburg
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

if [ $# -eq 0 ]
then
  echo "Usage: $0 file [...]" >&2
  echo "Clean up C sources in given files." >&2
  exit 1
fi

for FILE in $*
do
  TMPFILE=`mktemp -t tmpfile.XXXXXX`
  sed -e s/[[:space:]]*$//      \
      -e 's/if(/if (/'          \
      -e 's/sizeof(/sizeof (/g' \
      -e 's/switch(/switch (/'  \
      -e 's/while(/while (/'    \
      -e 's/for(/for (/'        \
      -e 's/do{/do {/'          \
      -e 's/){/) {/'            \
      $FILE > $TMPFILE
  mv -f $TMPFILE $FILE
done
