def makesuffixeratorarglisttable(dbdna)
  arglisttable =
  [
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -dna -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna} -bck -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl -tis -bsize 10 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 8 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 9 -blbuck 10 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 8 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 9 -locfreq 32",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 4",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 8",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 16",
   " -smap TransDNA -db #{dbdna}  -pl  -bsize 10 -blbuck 10 -locfreq 32",
  ]
  return arglisttable
end

