#!/usr/bin/env perl
#
# Copyright (c) 2006-2007 Gordon Gremme <gremme@zbh.uni-hamburg.de>
# Copyright (c) 2006-2007 Center for Bioinformatics, University of Hamburg
# See LICENSE file or http://genometools.org/license.html for license details.
#

# checks the supplied files for two empty lines in a row

use strict;
use warnings;

my $empty_line_found = 0;
my $error_code = 0;
while (<>) {
  if (m/^\n$/) {
    if ($empty_line_found) {
      printf "$ARGV: $.: two empty lines in a row\n";
      $error_code = 1;
    }
    $empty_line_found = 1;
  }
  else {
    $empty_line_found = 0;
  }
}
continue {
  close ARGV if eof; # to reset line numbers between files
}
exit $error_code;
