/*
  Copyright (c) 2012 Sascha Steinbiss <steinbiss@zbh.uni-hamburg.de>
  Copyright (c) 2012 Center for Bioinformatics, University of Hamburg

  Permission to use, copy, modify, and distribute this software for any
  purpose with or without fee is hereby granted, provided that the above
  copyright notice and this permission notice appear in all copies.

  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

#ifndef ANNO_DB_PREPARED_STMT_H
#define ANNO_DB_PREPARED_STMT_H

enum GtAnnoDBPreparedStmt {
  GT_PSTMT_TYPE_SELECT,
  GT_PSTMT_TYPE_INSERT,
  GT_PSTMT_SOURCE_SELECT,
  GT_PSTMT_SOURCE_INSERT,
  GT_PSTMT_PARENT_INSERT,
  GT_PSTMT_SEQUENCEREGION_SELECT,
  GT_PSTMT_GET_SEQREG_RANGE_SELECT,
  GT_PSTMT_SEQUENCEREGION_INSERT,
  GT_PSTMT_FEATURE_INSERT,
  GT_PSTMT_FEATURE_UPDATE,
  GT_PSTMT_RANGE_INSERT,
  GT_PSTMT_ATTRIBUTE_INSERT,
  GT_PSTMT_GET_ALL,
  GT_PSTMT_GET_RANGE_SELECT,
  GT_PSTMT_GET_ATTRIBUTE_SELECT,
  GT_PSTMT_GET_PARENTS_SELECT,
  GT_PSTMT_GET_PARENTS_COUNT,
  GT_PSTMT_GET_SEQIDS_SELECT,
  GT_PSTMT_GET_BY_SEQID_SELECT,
  GT_PSTMT_HAS_SEQID_SELECT,
  GT_PSTMT_GET_FIRST_SEQID_SELECT,
  GT_PSTMT_NODE_DELETE_FEATURE,
  GT_PSTMT_NODE_DELETE_RANGE,
  GT_PSTMT_NODE_DELETE_AS_CHILD,
  GT_PSTMT_NODE_DELETE_AS_PARENT,
  GT_PSTMT_NODE_UPDATE_SCORE,
  GT_PSTMT_NODE_UPDATE_STRAND,
  GT_PSTMT_NODE_UPDATE_PHASE,
  GT_PSTMT_NODE_UPDATE_ATTRIB,
  GT_PSTMT_NODE_DELETE_ATTRIB,
  GT_PSTMT_NODE_DELETE_ATTRIB_FOR_NODE,
  GT_PSTMT_NODE_ADD_CHILD,
  GT_PSTMT_NOF_STATEMENTS
};

#endif
